### ISSUE TITLE
tiles for the tileCollection

### ISSUE THREAD

**Issue by JumpLink** [williammalone/BlocksJS#1]
I know you've started this implementation, just now. But I'm interested in this feature.
I work on a hobby project and I use the map editor called [Tiled](http://www.mapeditor.org/) (which is really great).
Maybe I generate big rasterized images of my tile based maps or I render the tiles directly, I'm still not sure what the better solution is.
If I want to use tileCollection, I need a array of tile objects for the tile collection, how I must implement the tile objects?

**Comment by williammalone** [comment]
A tile object is an object with two properties: 
1. "src" is the path and filename of the image
2. "id" is an optional property which can be used when defining the order of the tiles in the tileCollection

Here is an example of a tileCollection consisting of 4 tile instances.  The top two tiles are the same sky image and the bottom two tiles are two different ground images:

``` javascript
var background = BLOCKS.tileCollection({
    order: [["sky", "sky"], ["groundLeft", "groundRight"]],
    tiles: [{
        id: "sky",
        src: "mars-surface.png"
    }, {
        id: "groundLeft",
        src: "ground-left.png"
    },  {
        id: "groundRight",
        src: "ground-right.png"
    }]
};
```

**Comment by JumpLink** [comment]
Do I need to use BLOCKS.preloader first or something like this? I get this error: ["Cannot read property 'width' of undefined"](https://github.com/williammalone/BlocksJS/blob/master/src/js/tileCollection.js#L77)

**Comment by williammalone** [comment]
Yes, that should fix the issue.  The tileCollection expects a preload loaded image since it uses the image dimensions to define the tile size.  I'll look into adding a warning.  You can use the BLOCK.preloader or if you want to preload the images yourself just assign the preloaded image to and "image" property for each of the tile definitions.

**Comment by williammalone** [comment]
I removed the requirement for preloading the first tile image before creating a tileCollection in release 0.5.13.  The image will still need to be loaded but the tileCollection should stay out of error town until the first tile image is loaded.

@JumpLink Please let me know this resolves your issues.
