### ISSUE TITLE
play sprite in sync with audio?

### ISSUE THREAD

**Issue by power7714** [williammalone/BlocksJS#2]
How would I have a character come in from the left side of the screen and stop in the middle then play the sprite animation with an audio file at the same time then have the animation stop once the audio file stops?

**Comment by williammalone** [comment]
You can provide a callback to the audio player's play method which will be called after the sound is completed. Inside that callback function you could stop the animation. If you were using a frame-based animation with a block or slice you could call the stop method. For example:

```
game.speaker.play("sound-name", function () {
  animation.stop();
});

```
