### ISSUE TITLE
Documentation site inactive

### ISSUE THREAD

**Issue by trevrdspcdev** [williammalone/BlocksJS#3]
Hey @williammalone, I'm curious if you still have a copy of the documentation for BlocksJS somewhere? It seems that [blocksjs.com](http://blocksjs.com/) is no longer hosted, so the documentation is no longer accessible there. I tried using https://wayback-api.archive.org/, but kept getting the error "Configuration File Not Found" on the Docs page.

**Comment by williammalone** [comment]
Looking for a new home for the docs, but until then you can find the docs at [www.williammalone.com/blocksjs](https://www.williammalone.com/blocksjs/).
